### ISSUE TITLE
Decide what information should be shown in the console.log

### ISSUE THREAD

**Issue by pvukmanovic-pannonians** [Pannonians/learning-js#63]
Create a normalized object called "generalData" that will contain data and information regarding movies and tv series.
Create a specialized objects called "tvData" and "movieData" that will show details specific to movies or series, depending what's fetched.

**Comment by Ninolina88** [comment]
**general data:**
title
year
description
image
cast

*This is what the team decided to show at the end of the project.

**Comment by pvukmanovic-pannonians** [comment]
> **general data:** title year description image cast
> 
> *This is what the team decided to show at the end of the project.

Might I suggest adding movie and tv series genres?

**Comment by Ninolina88** [comment]
the team decided to include genres as suggested. Also, we will try to present a review with the stars.
